apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    app: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: ghost:3.15.3-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2368
        env:
        - name: url
          value: http://127.0.0.1:2368
        volumeMounts:
            - mountPath: /var/lib/ghost/content
              name: content
      volumes:
      - name: content
        persistentVolumeClaim:
          claimName: blog-content
    